import type { GetServerSideProps } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { FormEvent, ReactNode, useEffect, useMemo, useRef, useState } from 'react';

// Satu file frontend untuk semua halaman agar jumlah file tetap sedikit.
const MangaDistrictScraper = require('../lib/mangadistrict.js');

const SITE = {
  name: 'PAZM',
  full: 'PAZM (PAZjar Manga)',
  desc: 'PAZM (PAZjar Manga) dibuat oleh Pajar untuk gabut dan pembelajaran saja. Modern manga reader cepat, ringan, dan berbasis backend scraper.',
  url: (process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000').replace(/\/$/, ''),
  dev: 'Developer by Pajar', github: '@pajarr10', instagram: '@snapshot.by.jare', wa: '+62 857-0855-7587',
  githubUrl: 'https://github.com/pajarr10', instagramUrl: 'https://www.instagram.com/snapshot.by.jare', waUrl: 'https://wa.me/6285708557587',
  adImg: process.env.NEXT_PUBLIC_AD_IMAGE_URL || '/ad-pazm.svg'
};
const ORDER = ['latest', 'title', 'trending', 'rating', 'views', 'new', 'modified'];
const ADULT = ['18+', 'adult', 'nsfw', 'uncensored', 'mature', 'ecchi', 'hentai', 'smut', 'dewasa', 'erotic', 'xxx'];
const GENRES = ['Action','Adventure','Comedy','Drama','Fantasy','Romance','School Life','Shounen','Shoujo','Seinen','Slice of Life','Supernatural','Mystery','Horror','Isekai','Manhwa','Manhua','Adult','18+','Mature','Ecchi','Hentai','Uncensored'];
const TAGS = ['Magic','Reincarnation','Regression','System','Dungeon','Villainess','Royalty','Monster','Game','Harem','NSFW','Adult','18+','Mature','Ecchi','Uncensored'];

type AnyObj = Record<string, any>;

function s(v: any, fallback = '') { return String(Array.isArray(v) ? v[0] : v ?? fallback).trim(); }
function page(v: any) { const n = Number(s(v, '1').replace(/\D/g, '')); return Number.isFinite(n) && n > 0 ? Math.min(999, n) : 1; }
function ord(v: any) { const x = s(v, 'latest'); return ORDER.includes(x) ? x : 'latest'; }
function termSlug(name: string) { return name.toLowerCase().trim().replace(/&/g, 'and').replace(/[^a-z0-9+]+/g, '-').replace(/^-+|-+$/g, '').replace(/\+/g, 'plus'); }
function cleanSlug(v: any) { return s(v).replace(/[^a-zA-Z0-9+_.~%:-]/g, '').slice(0, 180); }
function safeUrl(v: any) { try { const u = new URL(s(v)); return ['http:', 'https:'].includes(u.protocol) ? u.toString() : ''; } catch { return ''; } }
function isAdultText(v?: string) { const t = String(v || '').toLowerCase(); return ADULT.some((x) => t.includes(x)); }
function isAdult(item?: AnyObj) { const terms = [...(item?.genres || []), ...(item?.tags || []), ...(item?.badges || []), item?.title, item?.type, item?.status].filter(Boolean); return terms.some((x) => isAdultText(String(x))); }
function adultBadges(item?: AnyObj) { if (!isAdult(item)) return []; const terms = [...(item?.genres || []), ...(item?.tags || []), ...(item?.badges || []), item?.title].join(' ').toLowerCase(); const out = []; if (terms.includes('18+')) out.push('18+'); if (terms.includes('nsfw')) out.push('NSFW'); if (terms.includes('adult') || terms.includes('mature') || terms.includes('dewasa')) out.push('Adult'); if (!out.length) out.push('18+'); return out.slice(0, 3); }
function safeOnly(items: AnyObj[] = []) { return items.filter((x) => !isAdult(x)); }
function img(src?: string | null) { if (!src) return undefined; return src.startsWith('/') ? src : `/api/image?url=${encodeURIComponent(src)}`; }
function slugFromLink(link?: string) { if (!link) return ''; const m = link.match(/\/series\/([^/?#]+)/i); return m?.[1] ? decodeURIComponent(m[1]) : ''; }
function mangaHref(link?: string) { const slug = slugFromLink(link); return slug ? `/manga/${encodeURIComponent(slug)}` : '/series'; }
function readHref(url?: string, manga?: string, adult = false) { if (!url) return '#'; const q = new URLSearchParams({ url }); if (manga) q.set('manga', manga); if (adult) q.set('adult', '1'); return `/read?${q}`; }
function uniq(items: AnyObj[], key = 'link') { const seen = new Set(); return items.filter((x) => { const k = x?.[key] || x?.title; if (!k || seen.has(k)) return false; seen.add(k); return true; }); }
function trunc(v?: string, n = 130) { const t = String(v || '').trim(); return t.length > n ? `${t.slice(0, n).trim()}…` : t; }
function num(v: any) { const t = String(v || '').toLowerCase().replace(/,/g, '.'); const n = Number(t.match(/[0-9]+(?:\.[0-9]+)?/)?.[0] || 0); return t.includes('m') ? n * 1_000_000 : t.includes('k') ? n * 1_000 : n; }
function taxTerm(name: string, kind: 'genre' | 'tag') { return { name, slug: termSlug(name), kind, adult: isAdultText(name) }; }
function items(res: AnyObj) { return res?.data?.items || []; }
async function scrape(command: string, ...args: any[]) { const sc = new MangaDistrictScraper(); return await sc[command](...args); }
async function withSafe<T>(p: Promise<T>) { try { return await p; } catch { return null as any; } }
async function fetchTaxonomyServer(origin: string) { try { const r = await fetch(`${origin}/api/taxonomy`); return (await r.json()).data; } catch { return { genres: GENRES.map((g) => taxTerm(g, 'genre')), tags: TAGS.map((t) => taxTerm(t, 'tag')) }; } }

function Icon({ name }: { name: string }) {
  const d: AnyObj = { home:'M3 10.5 12 3l9 7.5V21h-6v-6H9v6H3V10.5Z', search:'M10.5 18a7.5 7.5 0 1 1 5.3-12.8 7.5 7.5 0 0 1-5.3 12.8Zm6-1.9 4.2 4.2-1.4 1.4-4.2-4.2Z', star:'m12 2 3.1 6.4 7 .9-5.1 5 1.3 7-6.3-3.4L5.7 21l1.3-7-5.1-5 7-.9L12 2Z', eye:'M12 5c5 0 9 4.5 10 7-1 2.5-5 7-10 7S3 14.5 2 12c1-2.5 5-7 10-7Zm0 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z', book:'M5 3h12a2 2 0 0 1 2 2v16H7a3 3 0 0 1-3-3V5c0-.7.4-1.4 1-1.7V18a1 1 0 0 0 1 1h11v-2H7V3Z', play:'M8 5v14l11-7L8 5Z', heart:'M12 21s-8-4.8-8-11a4.8 4.8 0 0 1 8-3.6A4.8 4.8 0 0 1 20 10c0 6.2-8 11-8 11Z', share:'M18 16.1c-.8 0-1.5.3-2 .8L8.9 12.8a3.3 3.3 0 0 0 0-1.6L16 7.1A3 3 0 1 0 15 5.4L7.9 9.5a3 3 0 1 0 0 5l7.1 4.1a3 3 0 1 0 3-2.5Z', left:'M11 5 4 12l7 7 1.4-1.4L7.8 13H20v-2H7.8l4.6-4.6Z', right:'m13 5 7 7-7 7-1.4-1.4 4.6-4.6H4v-2h12.2l-4.6-4.6Z', tag:'M20.6 13.2 13.2 20.6a2 2 0 0 1-2.8 0l-7-7A2 2 0 0 1 2.8 12V5a2 2 0 0 1 2-2h7a2 2 0 0 1 1.4.6l7.4 7.4a2 2 0 0 1 0 2.8ZM7.5 9A1.5 1.5 0 1 0 7.5 6a1.5 1.5 0 0 0 0 3Z', close:'m6.4 5 12.6 12.6-1.4 1.4L5 6.4Zm12.6 1.4L6.4 19 5 17.6 17.6 5Z', warn:'M12 2 1 21h22L12 2Zm1 15h-2v2h2Zm0-8h-2v6h2Z' };
  return <svg viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d={d[name] || d.home} /></svg>;
}
function SEO({ title, desc = SITE.desc, path = '/', image: imageUrl }: AnyObj) { const t = title ? `${title} — ${SITE.name}` : `${SITE.full} — Manga Reader`; const url = `${SITE.url}${path}`; return <Head><title>{t}</title><meta name="description" content={desc} /><meta name="robots" content="index,follow,max-image-preview:large" /><link rel="canonical" href={url} /><meta property="og:type" content="website" /><meta property="og:site_name" content={SITE.full} /><meta property="og:title" content={t} /><meta property="og:description" content={desc} /><meta property="og:url" content={url} /><meta property="og:image" content={imageUrl || `${SITE.url}/ad-pazm.svg`} /><meta name="twitter:card" content="summary_large_image" /><meta name="theme-color" content="#0d0709" /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ '@context':'https://schema.org', '@type':'WebSite', name:SITE.full, url:SITE.url, potentialAction:{ '@type':'SearchAction', target:`${SITE.url}/search?q={search_term_string}`, 'query-input':'required name=search_term_string' } }) }} /></Head>; }
function Button({ href, children, primary, outline, onClick, disabled, type = 'button' }: AnyObj) { const c = `btn ${primary ? 'primary' : ''} ${outline ? 'outline' : ''}`; if (href) return /^https?:/.test(href) ? <a className={c} href={href} target="_blank" rel="noreferrer">{children}</a> : <Link className={c} href={href}>{children}</Link>; return <button className={c} onClick={onClick} disabled={disabled} type={type}>{children}</button>; }
function Badge({ children, red, gold, green }: AnyObj) { return <span className={`badge ${red ? 'red' : ''} ${gold ? 'gold' : ''} ${green ? 'green' : ''}`}>{children}</span>; }

function SearchBox({ mobileClose }: AnyObj) {
  const router = useRouter(); const [q, setQ] = useState(''); const [open, setOpen] = useState(false); const [res, setRes] = useState<AnyObj[]>([]); const [hist, setHist] = useState<string[]>([]);
  useEffect(() => { try { setHist(JSON.parse(localStorage.getItem('pazm:search') || '[]')); } catch {} }, []);
  useEffect(() => { if (q.trim().length < 2) { setRes([]); return; } const t = setTimeout(async () => { try { const r = await fetch(`/api/search?query=${encodeURIComponent(q)}`); const j = await r.json(); setRes((j.data?.items || []).slice(0, 6)); } catch { setRes([]); } }, 300); return () => clearTimeout(t); }, [q]);
  const go = (v = q) => { const query = v.trim(); if (!query) return; const h = [query, ...hist.filter((x) => x.toLowerCase() !== query.toLowerCase())].slice(0, 8); try { localStorage.setItem('pazm:search', JSON.stringify(h)); } catch {} setHist(h); setOpen(false); mobileClose?.(); router.push(`/search?q=${encodeURIComponent(query)}`); };
  return <div className="searchbox" onBlur={() => setTimeout(() => setOpen(false), 160)}><form onSubmit={(e) => { e.preventDefault(); go(); }}><input value={q} onFocus={() => setOpen(true)} onChange={(e) => { setQ(e.target.value); setOpen(true); }} placeholder="Search manga..." aria-label="Search manga" /><button aria-label="Search"><Icon name="search" /></button></form>{open && (q.length > 1 || hist.length > 0) && <div className="suggest"><b>{q.length > 1 ? 'Suggestion' : 'Recent Search'}</b>{q.length > 1 ? (res.length ? res.map((x) => <Link className="suggest-row" href={mangaHref(x.link)} key={x.link} onClick={mobileClose}>{x.poster ? <img src={img(x.poster)} alt="" /> : <span /> }<em>{x.title}<small>{[x.status, x.year, x.genres?.[0]].filter(Boolean).join(' • ')}</small></em>{isAdult(x) && <Badge red>{adultBadges(x)[0]}</Badge>}</Link>) : <p>Tidak ada hasil.</p>) : hist.map((x) => <button className="suggest-row" type="button" key={x} onMouseDown={() => go(x)}><span /><em>{x}</em><Icon name="right" /></button>)}</div>}</div>;
}
function Nav() { const router = useRouter(); const [m, setM] = useState(false); const links = [['/','Home'],['/latest','Latest'],['/popular','Popular'],['/genre','Genre'],['/tags','Tags'],['/series','Series'],['/release','Release'],['/profile','Profile']]; const active = (h: string) => h === '/' ? router.asPath.split('?')[0] === '/' : router.asPath.startsWith(h); return <><header className="nav"><div className="wrap navin"><Link href="/" className="logo"><span>P</span>PAZ<b>M</b></Link><div className="desktop-search"><SearchBox /></div><nav>{links.map(([h,l]) => <Link className={active(h) ? 'on' : ''} href={h} key={h}>{l}</Link>)}</nav><button className="iconbtn mob" onClick={() => setM(!m)}><Icon name={m ? 'close' : 'search'} /></button></div></header>{m && <div className="mobile-search"><SearchBox mobileClose={() => setM(false)} /></div>}<div className="bottom">{[['/','home','Home'],['/latest','book','Latest'],['/series','tag','Series'],['/genre','tag','Genre'],['/profile','heart','Profile']].map(([h,i,l]) => <Link className={active(h) ? 'on' : ''} href={h} key={h}><Icon name={i}/><small>{l}</small></Link>)}</div></>; }
function Layout({ children }: { children: ReactNode }) { return <div className="app"><Nav /><main>{children}</main><Footer /><AdPopup /></div>; }
function Footer() { return <footer><div className="wrap foot"><div><b>{SITE.full}</b><p>{SITE.dev}. Web ini dibuat oleh Pajar bertujuan untuk gabut dan pembelajaran saja.</p><p>Semua data manga berasal dari backend scraper, tanpa database manga buatan sendiri.</p></div><div className="footlinks"><Link href="/series">Series</Link><Link href="/genre">Genre</Link><Link href="/tags">Tags</Link><a href={SITE.githubUrl}>Github {SITE.github}</a><a href={SITE.instagramUrl}>Instagram {SITE.instagram}</a><a href={SITE.waUrl}>WhatsApp</a></div></div></footer>; }
function AdPopup() { const [show, setShow] = useState(false); const [sec, setSec] = useState(5); useEffect(() => { const day = new Intl.DateTimeFormat('en-CA', { timeZone:'Asia/Jakarta' }).format(new Date()); let count = 0; try { const x = JSON.parse(localStorage.getItem('pazm:ad') || '{}'); count = x.day === day ? Number(x.count || 0) : 0; if (count < 2) localStorage.setItem('pazm:ad', JSON.stringify({ day, count: count + 1 })); } catch {} if (count < 2) setTimeout(() => setShow(true), 450); }, []); useEffect(() => { if (!show || sec <= 0) return; const t = setTimeout(() => setSec(sec - 1), 1000); return () => clearTimeout(t); }, [show, sec]); if (!show) return null; return <div className="ad"><div className="adcard"><img src={SITE.adImg} alt="PAZM Ads"/><div><h2>MAFF GUYS IKLAN..</h2><p>Dukung PAZM supaya tetap hidup. Popup ini muncul maksimal 2 kali sehari.</p><div className="adacts"><Button primary href="https://t.me/dilzautoorderbot">Telegram</Button><Button outline href="https://wa.me/6281584699368">WhatsApp</Button></div><Button disabled={sec > 0} onClick={() => setShow(false)}>{sec > 0 ? `Close aktif ${sec}s` : 'Close'}</Button></div></div></div>; }

function Card({ x }: { x: AnyObj }) { const [bad, setBad] = useState(false); const adult = isAdult(x); const mslug = slugFromLink(x.link); return <article className="card"><Link href={mangaHref(x.link)}><div className="poster">{!bad && x.poster ? <img src={img(x.poster)} alt={x.title} loading="lazy" onError={() => setBad(true)} /> : <div>{trunc(x.title, 35)}</div>}<div className="badges">{adultBadges(x).map((b) => <Badge red key={b}>{b}</Badge>)}{x.rating && <Badge gold><Icon name="star" />{x.rating}</Badge>}</div></div></Link><div className="cb"><Link href={mangaHref(x.link)}><h3>{x.title}</h3></Link><p>{[x.status, x.year, x.genres?.[0]].filter(Boolean).join(' • ') || 'Series'}</p>{x.latestChapter?.url && <Link className="chap" href={readHref(x.latestChapter.url, mslug, adult)}>{x.latestChapter.title || 'Read'} <Icon name="right"/></Link>}</div></article>; }
function Grid({ list, row = false }: { list: AnyObj[]; row?: boolean }) { return list?.length ? <div className={row ? 'rowgrid' : 'grid'}>{list.map((x) => <Card x={x} key={x.link || x.title} />)}</div> : <Empty title="Data kosong" msg="Scraper tidak mengirim item untuk bagian ini." />; }
function Section({ title, sub, href, children }: AnyObj) { return <section className="sec"><div className="sechead"><div><h2>{title}</h2>{sub && <p>{sub}</p>}</div>{href && <Link href={href}>Lihat Semua ›</Link>}</div>{children}</section>; }
function Empty({ title, msg }: AnyObj) { return <div className="empty"><b>{title}</b><span>{msg}</span></div>; }
function Hero({ x }: { x?: AnyObj }) { if (!x) return null; const mslug = slugFromLink(x.link); return <section className="hero"><div className="heroimg" style={{ backgroundImage: x.poster ? `url(${img(x.poster)})` : undefined }} /><div className="heroin"><span className="kicker">PAZM Highlight</span><h1>{x.title}</h1><p>{trunc([x.genres?.slice(0,4).join(' • '), x.status, x.year].filter(Boolean).join(' — '), 160) || SITE.desc}</p><div><Button primary href={mangaHref(x.link)}><Icon name="book"/>Detail Series</Button>{x.latestChapter?.url && <Button outline href={readHref(x.latestChapter.url, mslug)}><Icon name="play"/>Mulai Baca</Button>}</div></div></section>; }
function TaxCloud({ terms, base, safe = false, limit }: AnyObj) { const list = (terms || []).filter((t: AnyObj) => !safe || !t.adult).slice(0, limit || 999); return <div className="cloud">{list.map((t: AnyObj) => <Link className={t.adult ? 'adult' : ''} href={`${base}/${encodeURIComponent(t.slug)}`} key={`${base}-${t.slug}`}>{t.name}{t.adult && <small>18+</small>}</Link>)}</div>; }
function Filter({ values }: AnyObj) { const router = useRouter(); const [v, setV] = useState(values); const set = (k: string, val: string) => setV((p: AnyObj) => ({ ...p, [k]: val })); const submit = (e: FormEvent) => { e.preventDefault(); const q: AnyObj = { ...router.query, page: undefined }; Object.entries(v).forEach(([k,val]) => { if (!val || val === 'all' || (k === 'orderby' && val === 'latest') || (k === 'direction' && val === 'desc')) delete q[k]; else q[k] = val; }); router.push({ pathname: router.asPath.split('?')[0], query: q }); }; return <form className="filter" onSubmit={submit}>{[['orderby','Order By',ORDER],['direction','Direction',['desc','asc']],['status','Status',['all','ongoing','completed','hiatus']],['type','Type',['all','manga','manhwa','manhua','webtoon']]].map(([k,l,opts]: any) => <label key={k}>{l}<select value={v[k]} onChange={(e) => set(k, e.target.value)}>{opts.map((o: string) => <option key={o} value={o}>{o}</option>)}</select></label>)}<label>Min Rating<input type="number" min="0" max="10" step="0.1" value={v.minRating} onChange={(e) => set('minRating', e.target.value)} /></label><label>Min Views<input type="number" min="0" step="1000" value={v.minViews} onChange={(e) => set('minViews', e.target.value)} /></label><label>Release<input value={v.release} onChange={(e) => set('release', e.target.value)} placeholder="2026 / all" /></label><label>Filter Page<input value={v.keyword} onChange={(e) => set('keyword', e.target.value)} placeholder="judul/genre/author" /></label><Button primary type="submit">Apply</Button></form>; }
function applyFilters(list: AnyObj[], q: AnyObj, safe = false) { let out = list.filter((x) => { if (safe && isAdult(x)) return false; if (q.status && q.status !== 'all' && !String(x.status || '').toLowerCase().includes(String(q.status).toLowerCase())) return false; if (q.type && q.type !== 'all' && !String(x.type || '').toLowerCase().includes(String(q.type).toLowerCase())) return false; if (q.minRating && Number(x.rating || 0) < Number(q.minRating)) return false; if (q.minViews && num(x.views) < Number(q.minViews)) return false; if (q.release && q.release !== 'all' && String(x.year || x.release || '') !== String(q.release)) return false; if (q.keyword) { const hay = [x.title,x.author,x.artist,x.status,x.year,...(x.genres||[]),...(x.tags||[])].join(' ').toLowerCase(); if (!hay.includes(String(q.keyword).toLowerCase())) return false; } return true; }); if (q.direction === 'asc') out = [...out].reverse(); return out; }
function Listing({ title, desc, data, safe = false }: AnyObj) { const router = useRouter(); const p = page(router.query.page); const q = { orderby: ord(router.query.orderby), direction: s(router.query.direction,'desc'), status:s(router.query.status,'all'), type:s(router.query.type,'all'), minRating:s(router.query.minRating), minViews:s(router.query.minViews), release:s(router.query.release,'all'), keyword:s(router.query.keyword) }; const list = applyFilters(items(data), q, safe); return <Layout><SEO title={title} desc={desc} path={router.asPath.split('?')[0]} /><div className="wrap top"><span className="kicker">Catalog</span><h1>{title}</h1><p className="lead">{desc}</p><Filter values={q}/><Grid list={list}/><div className="pages">{p > 1 && <Button outline href={`${router.asPath.split('?')[0]}?${new URLSearchParams({ ...router.query, page:String(p-1) } as any)}`}>‹ Prev</Button>}<b>Page {p}</b>{(data?.data?.next || items(data).length) && <Button primary href={`${router.asPath.split('?')[0]}?${new URLSearchParams({ ...router.query, page:String(p+1) } as any)}`}>Next ›</Button>}</div></div></Layout>; }
function Home({ props }: AnyObj) { const all = uniq([...safeOnly(props.latest), ...safeOnly(props.popular), ...safeOnly(props.trending), ...safeOnly(props.recent), ...safeOnly(props.modified)]); const completed = all.filter((x) => /complete/i.test(String(x.status || x.badges?.join(' ')))); const ongoing = all.filter((x) => /ongoing|on-going/i.test(String(x.status || x.badges?.join(' ')))); return <Layout><SEO title="Home"/><div className="wrap top"><Hero x={all[0]} /><Section title="Latest Update" sub="Update terbaru aman untuk home." href="/latest"><Grid row list={safeOnly(props.latest).slice(0,12)}/></Section><Section title="Popular Manga" sub="Popular tanpa konten 18+ di home." href="/popular"><Grid row list={safeOnly(props.popular).slice(0,12)}/></Section><Section title="Trending" sub="Trending aman untuk pengguna umum." href="/series?orderby=trending"><Grid row list={safeOnly(props.trending).slice(0,12)}/></Section><Section title="Recently Added" sub="Series baru dari scraper." href="/series?orderby=new"><Grid row list={safeOnly(props.recent).slice(0,12)}/></Section><Section title="New Chapter" sub="Chapter baru, lazy loaded." href="/latest"><Grid row list={safeOnly(props.modified).slice(0,12)}/></Section><Section title="Completed" href="/series?status=completed"><Grid row list={completed.slice(0,12)}/></Section><Section title="Ongoing" href="/series?status=ongoing"><Grid row list={ongoing.slice(0,12)}/></Section><Section title="Genre List" sub="Home hanya menampilkan genre aman." href="/genre"><TaxCloud safe terms={props.taxonomy?.genres} base="/genre" limit={28}/></Section><Section title="Tag List" sub="Home hanya menampilkan tag aman." href="/tags"><TaxCloud safe terms={props.taxonomy?.tags} base="/tags" limit={28}/></Section></div></Layout>; }
function AgeGate({ id, children }: AnyObj) { const router = useRouter(); const [ok, setOk] = useState(false); useEffect(() => { try { setOk(localStorage.getItem(`pazm:age:${id}`) === '1'); } catch {} }, [id]); if (ok) return <>{children}</>; return <Layout><SEO title="Age Warning" noIndex/><div className="wrap top"><div className="age empty"><Badge red><Icon name="warn"/>18+ / Adult / NSFW</Badge><h1>This content contains adult material.</h1><p>You must be at least 18 years old to continue.</p><div><Button primary onClick={() => { try { localStorage.setItem(`pazm:age:${id}`, '1'); } catch {} setOk(true); }}>Continue</Button><Button outline onClick={() => router.back()}>Back</Button></div></div></div></Layout>; }
function Detail({ data }: AnyObj) { const d = data?.data || {}; const adult = isAdult(d); const slug = d.slug || slugFromLink(d.url); const first = d.chapters?.[0]; const content = <Layout><SEO title={d.title || 'Detail Manga'} desc={trunc(d.description, 155)} image={d.poster} path={`/manga/${slug}`}/><div className="wrap top"><section className="detail"><div className="bg" style={{ backgroundImage: d.banner || d.poster ? `url(${img(d.banner || d.poster)})` : undefined }}/><div className="detailin"><img className="cover" src={img(d.poster)} alt={d.title}/><div><div className="badges static">{adultBadges(d).map((b) => <Badge red key={b}>{b}</Badge>)}{d.rating && <Badge gold><Icon name="star"/>{d.rating}</Badge>}{d.status && <Badge green>{d.status}</Badge>}</div><h1>{d.title}</h1>{d.altNames?.length && <p className="lead">{d.altNames.join(', ')}</p>}<p>{d.description || 'Deskripsi tidak tersedia dari scraper.'}</p><div className="acts">{first?.url && <Button primary href={readHref(first.url, slug, adult)}><Icon name="book"/>Read</Button>}<Button outline onClick={() => { const bm = JSON.parse(localStorage.getItem('pazm:bookmark') || '[]'); localStorage.setItem('pazm:bookmark', JSON.stringify(uniq([{ title:d.title, link:d.url, poster:d.poster }, ...bm]))); alert('Bookmark disimpan lokal.'); }}><Icon name="heart"/>Bookmark</Button><Button outline onClick={() => navigator.share ? navigator.share({ title:d.title, url:location.href }) : navigator.clipboard.writeText(location.href)}><Icon name="share"/>Share</Button></div></div></div></section><div className="info">{[['Alternative Title',d.altNames?.join(', ')],['Status',d.status],['Type',d.type],['Author',d.author],['Artist',d.artist],['Views',d.views],['Release',d.year],['Rating',d.rating]].map(([a,b]) => <div key={a}><small>{a}</small><b>{b || '—'}</b></div>)}</div><Section title="Genre"><TaxCloud terms={(d.genres || []).map((g: string) => taxTerm(g,'genre'))} base="/genre"/></Section><Section title="Tag"><TaxCloud terms={(d.tags || []).map((t: string) => taxTerm(t,'tag'))} base="/tags"/></Section><Section title="Daftar Chapter"><div className="chapters">{(d.chapters || []).map((c: AnyObj, i: number) => c.url ? <Link className="chapter" key={c.url} href={readHref(c.url, slug, adult)}><span><b>{c.title || `Chapter ${i+1}`}</b><small>{c.date}</small></span><Icon name="right"/></Link> : <div className="chapter" key={i}>{c.title}</div>)}</div></Section>{d.related?.length && <Section title="Related Series"><Grid row list={d.related}/></Section>}</div></Layout>; return adult ? <AgeGate id={slug || d.title}>{content}</AgeGate> : content; }
function Profile() { return <Layout><SEO title="Profile"/><div className="wrap top profile"><span className="kicker">Profile</span><h1>{SITE.full}</h1><p>{SITE.dev}</p><p>Web ini dibuat oleh Pajar bertujuan untuk gabut dan pembelajaran saja.</p><div className="info"><div><small>Github</small><b>{SITE.github}</b></div><div><small>Instagram</small><b>{SITE.instagram}</b></div><div><small>WhatsApp</small><b>{SITE.wa}</b></div></div><div className="acts"><Button primary href={SITE.githubUrl}>Github</Button><Button outline href={SITE.instagramUrl}>Instagram</Button><Button outline href={SITE.waUrl}>WhatsApp</Button></div></div></Layout>; }
function TaxIndex({ taxonomy, kind }: AnyObj) { const isTag = kind === 'tags'; return <Layout><SEO title={isTag ? 'Tags' : 'Genre'}/><div className="wrap top"><span className="kicker">Filter</span><h1>{isTag ? 'Tags' : 'Genre'}</h1><p className="lead">Genre/tag dewasa seperti Adult, Mature, Ecchi, Uncensored, 18+ tetap tersedia dan diberi label.</p><TaxCloud terms={taxonomy?.[isTag ? 'tags' : 'genres']} base={isTag ? '/tags' : '/genre'} /></div></Layout>; }
function ReleaseIndex() { const y = new Date().getFullYear(); return <Layout><SEO title="Release"/><div className="wrap top"><span className="kicker">Release</span><h1>Release Year</h1><div className="cloud">{Array.from({ length: 28 }, (_, i) => String(y-i)).map((year) => <Link href={`/release/${year}`} key={year}>{year}</Link>)}</div></div></Layout>; }
function NotFound() { return <Layout><SEO title="404"/><div className="wrap top"><Empty title="404" msg="Halaman tidak ditemukan."/><p><Button primary href="/">Kembali Home</Button></p></div></Layout>; }

function ReaderPage({ data, query }: AnyObj) { const d = data?.data || {}; const adult = query.adult === '1'; return adult ? <AgeGate id={`read:${query.url}`}><ReaderCore d={d} query={query}/></AgeGate> : <ReaderCore d={d} query={query}/>; }
function ReaderCore({ d, query }: AnyObj) { const [progress, setProgress] = useState(0); const [dark, setDark] = useState(true); useEffect(() => { document.body.classList.add('readerbody'); const saved = JSON.parse(localStorage.getItem(`pazm:read:${query.url}`) || 'null'); if (saved?.scrollY) setTimeout(() => scrollTo(0, saved.scrollY), 300); const on = () => { const max = document.documentElement.scrollHeight - innerHeight; const p = max > 0 ? Math.min(100, Math.max(0, scrollY / max * 100)) : 0; setProgress(p); localStorage.setItem(`pazm:read:${query.url}`, JSON.stringify({ scrollY, progress:p, title:d.title, updatedAt:Date.now() })); }; const key = (e: KeyboardEvent) => { if (e.key === 'ArrowRight' && (d.nextChapter || d.nextEpisode)) location.href = readHref(d.nextChapter || d.nextEpisode, query.manga, query.adult === '1'); if (e.key === 'ArrowLeft' && (d.prevChapter || d.prevEpisode)) location.href = readHref(d.prevChapter || d.prevEpisode, query.manga, query.adult === '1'); }; addEventListener('scroll', on, { passive:true }); addEventListener('keydown', key); on(); return () => { document.body.classList.remove('readerbody'); removeEventListener('scroll', on); removeEventListener('keydown', key); }; }, [query.url, query.manga, query.adult, d.title, d.nextChapter, d.nextEpisode, d.prevChapter, d.prevEpisode]); const isVideo = d.videoSrc || d.iframeSrc || d.videoLinks?.length; return <main className={dark ? 'reader dark' : 'reader'}><SEO title={d.title || 'Reader'} noIndex/><div className="rbar"><div style={{ width:`${progress}%` }}/></div><header className="rtop"><Link className="iconbtn" href="/"><Icon name="home"/></Link><b>{d.title || 'PAZM Reader'}</b><span>{Math.round(progress)}%</span><button className="iconbtn" onClick={() => setDark(!dark)}>{dark ? '🌙' : '☀️'}</button></header>{isVideo ? <Video d={d}/> : <Images d={d}/>}<div className="rnav">{(d.prevChapter || d.prevEpisode) && <Button outline href={readHref(d.prevChapter || d.prevEpisode, query.manga, query.adult === '1')}>‹ Prev</Button>}{(d.nextChapter || d.nextEpisode) && <Button primary href={readHref(d.nextChapter || d.nextEpisode, query.manga, query.adult === '1')}>Next ›</Button>}</div></main>; }
function Images({ d }: AnyObj) { const imgs = d.images || []; if (!imgs.length) return <div className="rwrap"><Empty title="Chapter kosong" msg="Scraper tidak menemukan gambar/video."/></div>; return <div className="rwrap">{imgs.map((im: AnyObj) => <img className="pageimg" src={img(im.src)} alt={im.alt || `Page ${im.index}`} loading={im.index <= 2 ? 'eager' : 'lazy'} key={`${im.index}-${im.src}`} />)}</div>; }
function Video({ d }: AnyObj) { const ref = useRef<HTMLVideoElement|null>(null); const src = d.videoSrc || d.videoLinks?.find((x: string) => /\.(mp4|m3u8)(\?|$)/i.test(x)); const [speed,setSpeed] = useState('1'); useEffect(() => { if (ref.current) ref.current.playbackRate = Number(speed); }, [speed]); if (d.iframeSrc && !src) return <div className="video"><iframe src={d.iframeSrc} allowFullScreen allow="autoplay; fullscreen; picture-in-picture" title={d.title}/></div>; if (!src && d.images?.length) return <Images d={d}/>; if (!src) return <div className="rwrap"><Empty title="Video tidak tersedia" msg="Scraper tidak mengirim source video."/></div>; return <div className="video"><video ref={ref} src={src} controls playsInline preload="metadata"/><div className="acts"><label>Speed <select value={speed} onChange={(e) => setSpeed(e.target.value)}>{['0.5','0.75','1','1.25','1.5','2'].map((x) => <option key={x} value={x}>{x}x</option>)}</select></label><Button outline onClick={() => ref.current?.requestFullscreen?.()}>Fullscreen</Button></div></div>; }

export default function Page(props: AnyObj) {
  if (props.kind === 'home') return <Home props={props}/>;
  if (props.kind === 'listing') return <Listing {...props}/>;
  if (props.kind === 'detail') return <Detail data={props.data}/>;
  if (props.kind === 'profile') return <Profile/>;
  if (props.kind === 'tax') return <TaxIndex taxonomy={props.taxonomy} kind={props.taxKind}/>;
  if (props.kind === 'releaseIndex') return <ReleaseIndex/>;
  if (props.kind === 'reader') return <ReaderPage data={props.data} query={props.query}/>;
  return <NotFound/>;
}

export const getServerSideProps: GetServerSideProps = async ({ params, query, req }) => {
  const path = ((params?.path || []) as string[]).map(cleanSlug);
  const host = req.headers.host || 'localhost:3000'; const origin = `${req.headers['x-forwarded-proto'] || 'http'}://${host}`;
  const p = page(query.page);
  try {
    if (!path.length) {
      const [latest, popular, trending, recent, modified, taxonomy] = await Promise.all([withSafe(scrape('home', 1)), withSafe(scrape('series', 'views', 1)), withSafe(scrape('series', 'trending', 1)), withSafe(scrape('series', 'new', 1)), withSafe(scrape('series', 'modified', 1)), fetchTaxonomyServer(origin)]);
      return { props: { kind:'home', latest:items(latest), popular:items(popular), trending:items(trending), recent:items(recent), modified:items(modified), taxonomy } };
    }
    if (path[0] === 'latest') return { props:{ kind:'listing', title:'Latest Update', desc:'Update terbaru dari scraper, otomatis aman tanpa konten 18+.', data: await scrape('home', p), safe:true } };
    if (path[0] === 'popular') return { props:{ kind:'listing', title:'Popular Manga', desc:'Manga populer berdasarkan views dari scraper, otomatis aman tanpa konten 18+.', data: await scrape('series', 'views', p), safe:true } };
    if (path[0] === 'series') return { props:{ kind:'listing', title:'Series', desc:'Catalog lengkap. Konten 18+ hanya muncul jika pengguna masuk ke halaman Series/filter/search/detail.', data: await scrape('series', ord(query.orderby), p) } };
    if (path[0] === 'search') return { props:{ kind:'listing', title:`Search: ${s(query.q || query.query) || 'Manga'}`, desc:'Search manual dapat menemukan konten 18+ apabila tersedia dari backend scraper.', data: s(query.q || query.query) ? await scrape('search', s(query.q || query.query).slice(0,120), p) : { data:{ items:[] } } } };
    if (path[0] === 'genre' && !path[1]) return { props:{ kind:'tax', taxKind:'genre', taxonomy: await fetchTaxonomyServer(origin) } };
    if (path[0] === 'tags' && !path[1]) return { props:{ kind:'tax', taxKind:'tags', taxonomy: await fetchTaxonomyServer(origin) } };
    if (path[0] === 'genre') return { props:{ kind:'listing', title:`Genre: ${path[1]}`, desc:'Filter genre dari backend scraper. Genre dewasa tetap tersedia dan diberi badge.', data: await scrape('genre', path[1], ord(query.orderby), p) } };
    if (path[0] === 'tags') return { props:{ kind:'listing', title:`Tag: ${path[1]}`, desc:'Filter tag dari backend scraper. Tag dewasa tetap tersedia dan diberi badge.', data: await scrape('tag', path[1], ord(query.orderby), p) } };
    if (path[0] === 'release' && !path[1]) return { props:{ kind:'releaseIndex' } };
    if (path[0] === 'release') return { props:{ kind:'listing', title:`Release ${path[1]}`, desc:'Filter manga berdasarkan tahun rilis.', data: await scrape('release', path[1], ord(query.orderby), p) } };
    if (path[0] === 'manga' && path[1]) return { props:{ kind:'detail', data: await scrape('detail', path[1]) } };
    if (path[0] === 'profile') return { props:{ kind:'profile' } };
    if (path[0] === 'read') { const url = safeUrl(query.url); return { props:{ kind:'reader', data: url ? await scrape('chapter', url) : { data:{} }, query:{ url, manga:s(query.manga), adult:s(query.adult) } } }; }
  } catch (e) { return { props:{ kind:'404', error: e instanceof Error ? e.message : 'error' } }; }
  return { props:{ kind:'404' } };
};
